---

 - name: Installing apache server on centos/redhat
   yum:
     name: httpd
     state: installed
   when: ansible_os_family=="RedHat"
   notify: restart apache

 - name: Installing apache on ubuntu
   apt:
     name: apache2
     state: installed
   when: ansible_os_family=="Debian"
   notify: restart apache
