---

- hosts: all
  become: yes

  tasks:
    - name: Installing web server
      apt: name=apache2 state=installed update_cache=true
      when: ansible_os_family == "Debian"
    - name: Installing web server
      yum: name=httpd state=installed
      ignore_errors: yes
      when: ansible_os_family == "RedHat"
