---
- hosts: all
  become: true
  tasks:
    - name: list of users 
      user: name={{ item }} state=absent
      with_items:
        - test1
        - test2
        - test3 
        - test4 
        - test5 
