- hosts: all
  become: yes
  vars_files:
    - var1.yml

  tasks:
    - name: Installing packages via variables
      yum: name={{ name1 }} state=installed
    - name: Installing git
      yum: name={{ name2 }} state=absent
